"""new tables

Revision ID: 39099fc9edb3
Revises: c44e42e07406
Create Date: 2021-05-11 01:43:05.953876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39099fc9edb3'
down_revision = 'c44e42e07406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('point_value', sa.Integer(), nullable=False),
    sa.Column('driver_eta_restaurant', sa.Integer(), nullable=True),
    sa.Column('driver_eta_dropoff', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('point_cost', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rewards')
    op.drop_table('food_requests')
    # ### end Alembic commands ###
