"""Initial migration

Revision ID: 64284dae8d6e
Revises: 
Create Date: 2021-04-27 08:43:00.263747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64284dae8d6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('password', sa.LargeBinary(length=60), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('car_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
