"""status, food_type, food_quantity, pickup_time

Revision ID: 877c30f435a5
Revises: 39099fc9edb3
Create Date: 2021-05-13 01:30:31.116289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877c30f435a5'
down_revision = '39099fc9edb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_requests', sa.Column('food_quantity', sa.String(length=254), nullable=True))
    op.add_column('food_requests', sa.Column('food_type', sa.String(length=256), nullable=True))
    op.add_column('food_requests', sa.Column('pickup_time', sa.String(length=60), nullable=True))
    op.add_column('food_requests', sa.Column('status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_requests', 'status')
    op.drop_column('food_requests', 'pickup_time')
    op.drop_column('food_requests', 'food_type')
    op.drop_column('food_requests', 'food_quantity')
    # ### end Alembic commands ###
